version: '3'
services:
  api:
    user: root
    build: .
    ports:
      - "8080:8080"    
    volumes:
      - "$PWD/images:/usr/src/app/images"
      - "$PWD/small_images:/usr/src/app/small_images"